name: Assign new issues to organization project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - run: |-
            echo "$ITEM_ID"
            echo "$ITEM_ID2"
            echo "$ITEM_ID3"
            echo "$ITEM_ID4"
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
          ITEM_ID: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          PROJECT_ID: ${{ secrets.QUARX_PROJECT_ID }}
